In [1]:
import numpy as np

In [6]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
a.shape

(2, 3)

In [14]:
b = a[a[:,:] < 3]
b[1]=999
b

array([  1, 999])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b = np.where(a>3)
b

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))