In [1]:
import tensorflow as tf

C:\Users\30694\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\30694\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\30694\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\30694\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passi

C:\Users\30694\Anaconda3\Lib\site-packages

In [2]:
tf.enable_eager_execution()

In [3]:
tf.executing_eagerly()

True

In [4]:
x = tf.ones([3,5]) 
x

<tf.Tensor: id=2, shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [5]:
tf.nn.dropout(x, rate = 0.5).numpy() 

array([[0., 2., 2., 2., 0.],
       [2., 2., 2., 0., 0.],
       [2., 2., 0., 2., 0.]], dtype=float32)

In [6]:
tf.nn.selective_dropout(x, nacts=3, nchannels=15).numpy() 

hiiiiiiiii
Calling Selective Dropout!


NameError: name 'seed' is not defined

In [10]:
keep_prob = 0.3
seed=0
random_tensor = keep_prob

In [12]:
from tensorflow.python.ops import random_ops

In [14]:
def _get_noise_shape(x, noise_shape):
  # If noise_shape is none return immediately.
  if noise_shape is None:
    return array_ops.shape(x)

  try:
    # Best effort to figure out the intended shape.
    # If not possible, let the op to handle it.
    # In eager mode exception will show up.
    noise_shape_ = tensor_shape.as_shape(noise_shape)
  except (TypeError, ValueError):
    return noise_shape

  if x.shape.dims is not None and len(x.shape.dims) == len(noise_shape_.dims):
    new_dims = []
    for i, dim in enumerate(x.shape.dims):
      if noise_shape_.dims[i].value is None and dim.value is not None:
        new_dims.append(dim.value)
      else:
        new_dims.append(noise_shape_.dims[i].value)
    return tensor_shape.TensorShape(new_dims)

  return noise_shape

In [19]:
from tensorflow.python.ops import array_ops

In [21]:
noise_shape=None
noise_shape = _get_noise_shape(x, noise_shape)
noise_shape

<tf.Tensor: id=21, shape=(2,), dtype=int32, numpy=array([3, 5])>

In [22]:
random_tensor += random_ops.random_uniform(noise_shape, seed=seed, dtype=x.dtype)

In [23]:
random_tensor

<tf.Tensor: id=30, shape=(3, 5), dtype=float32, numpy=
array([[0.40086263, 1.2701669 , 1.1487641 , 0.34828132, 0.34852308],
       [1.0774746 , 1.1444681 , 0.71707493, 0.8099584 , 0.9552025 ],
       [1.2881508 , 0.6669894 , 0.6778979 , 0.99118716, 1.295444  ]],
      dtype=float32)>

In [25]:
from tensorflow.python.ops import math_ops

In [26]:
binary_tensor = math_ops.floor(random_tensor)
binary_tensor

<tf.Tensor: id=32, shape=(3, 5), dtype=float32, numpy=
array([[0., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1.]], dtype=float32)>

In [27]:
ret = math_ops.divide(x, keep_prob) * binary_tensor
ret

<tf.Tensor: id=36, shape=(3, 5), dtype=float32, numpy=
array([[0.       , 3.3333333, 3.3333333, 0.       , 0.       ],
       [3.3333333, 3.3333333, 0.       , 0.       , 0.       ],
       [3.3333333, 0.       , 0.       , 0.       , 3.3333333]],
      dtype=float32)>

In [28]:
random_tensor

<tf.Tensor: id=30, shape=(3, 5), dtype=float32, numpy=
array([[0.40086263, 1.2701669 , 1.1487641 , 0.34828132, 0.34852308],
       [1.0774746 , 1.1444681 , 0.71707493, 0.8099584 , 0.9552025 ],
       [1.2881508 , 0.6669894 , 0.6778979 , 0.99118716, 1.295444  ]],
      dtype=float32)>

In [29]:
tf.argmax(random_tensor)

<tf.Tensor: id=40, shape=(5,), dtype=int64, numpy=array([2, 0, 0, 2, 2], dtype=int64)>

In [31]:
import numpy as np
a = np.array([
    [
        [1,5],[7,3]
    ], 
    [
        [22,15], [21,4]
    ], 
    [
        [34,1], [7,8]
    ]
    
    
])

In [34]:
b = tf.convert_to_tensor(a)
b

<tf.Tensor: id=44, shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  5],
        [ 7,  3]],

       [[22, 15],
        [21,  4]],

       [[34,  1],
        [ 7,  8]]])>

In [46]:
b = tf.dtypes.cast(b, tf.float32)
b

<tf.Tensor: id=71, shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 1.,  5.],
        [ 7.,  3.]],

       [[22., 15.],
        [21.,  4.]],

       [[34.,  1.],
        [ 7.,  8.]]], dtype=float32)>

## Get the norm of input tensor along axis

In [48]:
c = tf.norm(b, axis=[1,2])
c

<tf.Tensor: id=83, shape=(3,), dtype=float32, numpy=array([ 9.165152, 34.146744, 35.63706 ], dtype=float32)>

## Find the top k values of a tensor

In [52]:
d=tf.math.top_k(c, k=2)  # default k=1
d

TopKV2(values=<tf.Tensor: id=100, shape=(2,), dtype=float32, numpy=array([35.63706 , 34.146744], dtype=float32)>, indices=<tf.Tensor: id=101, shape=(2,), dtype=int32, numpy=array([2, 1])>)

## And the indices of top k values

In [53]:
d.indices

<tf.Tensor: id=101, shape=(2,), dtype=int32, numpy=array([2, 1])>

In [56]:
kth = tf.reduce_min(d.values)
top2 = tf.greater_equal(c, kth)
top2

<tf.Tensor: id=113, shape=(3,), dtype=bool, numpy=array([False,  True,  True])>

In [58]:
kth

<tf.Tensor: id=112, shape=(), dtype=float32, numpy=34.146744>

In [57]:
# Casting False-True to 0-1
tf.cast(top2, tf.float32)

<tf.Tensor: id=115, shape=(3,), dtype=float32, numpy=array([0., 1., 1.], dtype=float32)>

In [1]:
import tensorflow as tf

C:\Users\30694\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\30694\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\30694\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\30694\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passi

C:\Users\30694\Anaconda3\Lib\site-packages

In [2]:
tf.enable_eager_execution()

In [3]:
tf.executing_eagerly()

True

In [4]:
import numpy as np
a = np.array([
    [
        [1,5],[7,3]
    ], 
    [
        [22,15], [21,4]
    ], 
    [
        [34,1], [7,8]
    ],
    [
        [11,8], [9,13]
    ],
    [
        [26,11], [17,1]
    ],
    [
        [41,2], [9,6]
    ],
    [
        [7,8], [19,13]
    ],
    [
        [22,28], [19,23]
    ],
    [
        [31,8], [9,3]
    ],
])



x = tf.convert_to_tensor(a)
x = tf.dtypes.cast(x, tf.float32)

In [5]:
tf.nn.dropout(x, rate = 0.5).numpy() 

x tf.Tensor(
[[[ 1.  5.]
  [ 7.  3.]]

 [[22. 15.]
  [21.  4.]]

 [[34.  1.]
  [ 7.  8.]]

 [[11.  8.]
  [ 9. 13.]]

 [[26. 11.]
  [17.  1.]]

 [[41.  2.]
  [ 9.  6.]]

 [[ 7.  8.]
  [19. 13.]]

 [[22. 28.]
  [19. 23.]]

 [[31.  8.]
  [ 9.  3.]]], shape=(9, 2, 2), dtype=float32)
binary_tensor tf.Tensor(
[[[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 1.]
  [0. 0.]]

 [[1. 0.]
  [1. 0.]]

 [[0. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]

 [[0. 1.]
  [0. 0.]]], shape=(9, 2, 2), dtype=float32)
ret:


array([[[ 0., 10.],
        [14.,  0.]],

       [[44.,  0.],
        [42.,  0.]],

       [[68.,  2.],
        [14., 16.]],

       [[22.,  0.],
        [ 0., 26.]],

       [[52., 22.],
        [ 0.,  0.]],

       [[82.,  0.],
        [18.,  0.]],

       [[ 0., 16.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0., 46.]],

       [[ 0., 16.],
        [ 0.,  0.]]], dtype=float32)

### keeping the top 3 activations

In [6]:
tf.nn.selective_dropout(x, nacts=3, nchannels=int(x.shape[0])).numpy() 

tf.Tensor(
[[[0.]]

 [[0.]]

 [[1.]]

 [[0.]]

 [[0.]]

 [[1.]]

 [[0.]]

 [[1.]]

 [[0.]]], shape=(9, 1, 1), dtype=float32)


array([[[  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.]],

       [[102.,   3.],
        [ 21.,  24.]],

       [[  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.]],

       [[123.,   6.],
        [ 27.,  18.]],

       [[  0.,   0.],
        [  0.,   0.]],

       [[ 66.,  84.],
        [ 57.,  69.]],

       [[  0.,   0.],
        [  0.,   0.]]], dtype=float32)

### keeping the top 6 activations

In [7]:
tf.nn.selective_dropout(x, nacts=6, nchannels=int(x.shape[0])).numpy() 

tf.Tensor(
[[[0.]]

 [[1.]]

 [[1.]]

 [[0.]]

 [[1.]]

 [[1.]]

 [[0.]]

 [[1.]]

 [[1.]]], shape=(9, 1, 1), dtype=float32)


array([[[ 0. ,  0. ],
        [ 0. ,  0. ]],

       [[33. , 22.5],
        [31.5,  6. ]],

       [[51. ,  1.5],
        [10.5, 12. ]],

       [[ 0. ,  0. ],
        [ 0. ,  0. ]],

       [[39. , 16.5],
        [25.5,  1.5]],

       [[61.5,  3. ],
        [13.5,  9. ]],

       [[ 0. ,  0. ],
        [ 0. ,  0. ]],

       [[33. , 42. ],
        [28.5, 34.5]],

       [[46.5, 12. ],
        [13.5,  4.5]]], dtype=float32)

### Generally It must be a hyperparameter to be tuned !!