In [1]:
Y = [4 , 22, 7, 30, 35,16.5]
Y_pred = [10,18,12,24,30,16] 

In [24]:
import numpy as np
import pandas as pd
import torch.nn as nn

In [3]:
Y=np.asarray(Y)

In [4]:
Y_pred=np.asarray(Y_pred)

In [5]:
Y

array([ 4. , 22. ,  7. , 30. , 35. , 16.5])

In [6]:
loss_func = torch.nn.MSELoss(reduction='mean')

In [7]:
Y_pred = torch.Tensor(Y_pred)
Y = torch.Tensor(Y)

In [8]:
test_loss = loss_func(Y_pred,Y)

In [9]:
test_loss

tensor(23.0417)

In [10]:
from torch.utils.data import Dataset, TensorDataset

class CustomDataset(Dataset):
    def __init__(self, x_tensor, y_tensor):
        self.x = x_tensor
        self.y = y_tensor
        
    def __getitem__(self, index):
        return (self.x[index], self.y[index])

    def __len__(self):
        return len(self.x)

In [11]:
data = CustomDataset(Y_pred , Y)

In [12]:
from torch.utils.data import DataLoader

#train_loader = DataLoader(dataset= data, batch_size=2, shuffle=True)
loader = DataLoader(dataset= data, batch_size=2, shuffle=True)

In [15]:
losses = []

for epoch in range(1):
    for x_batch, y_batch in loader:
        print(x_batch,y_batch)
        
        loss = loss_func(x_batch, y_batch)
        losses.append(loss)
        print(losses)
        print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
        

    print('epoch', epoch, 'loss', sum(losses)/3)


tensor([24., 16.]) tensor([30.0000, 16.5000])
[tensor(18.1250)]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tensor([30., 18.]) tensor([35., 22.])
[tensor(18.1250), tensor(20.5000)]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tensor([12., 10.]) tensor([7., 4.])
[tensor(18.1250), tensor(20.5000), tensor(30.5000)]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
epoch 0 loss tensor(23.0417)


In [17]:
loader2 = DataLoader(dataset= data, batch_size=len(Y))

for x_batch, y_batch in loader2:
    print(x_batch,y_batch)

    loss = loss_func(x_batch, y_batch)
    losses.append(loss)
    print(losses)
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')

tensor([10., 18., 12., 24., 30., 16.]) tensor([ 4.0000, 22.0000,  7.0000, 30.0000, 35.0000, 16.5000])
[tensor(18.1250), tensor(20.5000), tensor(30.5000), tensor(36.), tensor(16.), tensor(25.), tensor(36.), tensor(25.), tensor(0.2500), tensor(23.0417)]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


In [18]:
4//4

1

In [19]:
8//4

2

In [22]:
X_train = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
X_pred  = [2,3,4,1,2,3,4,5,8,5,12,13,4,16,17,14,16,17,19,18]
len(X_train)==len(X_pred)

True

## Create Feed Forward Neural Network

In [25]:
'''
STEP 3: CREATE MODEL CLASS
'''
class FeedforwardNeuralNetModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        
        super(FeedforwardNeuralNetModel, self).__init__()
    
        # Linear function 1: 784 --> 100
        self.fc1 = nn.Linear(input_dim, hidden_dim) 
        # Non-linearity 1
        self.relu1 = nn.LeakyReLU(0.2, inplace=True)

        # Linear function 2: 100 --> 100
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        # Non-linearity 2
        self.relu2 = nn.LeakyReLU(0.2, inplace=True)
        #self.relu2 = nn.ReLU()
        
        
        # Linear function 3: 100 --> 100
        self.fc3 = nn.Linear(hidden_dim, hidden_dim)
        # Non-linearity 3
        self.relu3 = nn.LeakyReLU(0.2, inplace=True)

        # Linear function 4 (readout): 100 --> 10
        self.fc4 = nn.Linear(hidden_dim, output_dim)  

In [26]:
    def forward(self, x):
        # Linear function 1
        out = self.fc1(x)
        # Non-linearity 1
        out = self.relu1(out)

        # Linear function 2
        out = self.fc2(out)
        # Non-linearity 2
        out = self.relu2(out)

        # Linear function 2
        out = self.fc3(out)
        # Non-linearity 2
        out = self.relu3(out)

        # Linear function 4 (readout)
        out = self.fc4(out)
        return out

In [27]:
4//2-1

1

In [30]:
lossaaa=[]
for epoch in range(6):
    if (epoch+1)%2 ==0:
        lossaaa.append(3*epoch)
    if (epoch+1)%2 ==0:
        print(lossaaa[(epoch+1)//2 -1])

3
9
15


In [ ]:
'''
STEP 1: LOADING DATASET
'''

data = read_csv('C://Users/30694/Desktop/DATASETS/LR.csv')

data_train = X_train.to_numpy()[:70]
print(len(data_train))

data_test = X_train.to_numpy()[70:]
print(len(data_test))


'''
STEP 2: MAKING DATASET ITERABLE
'''

batch_size = 20
n_iters = 3000
num_epochs = 2

train_loader = torch.utils.data.DataLoader(dataset=train_dataset, 
                                           batch_size=batch_size, 
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset, 
                                          batch_size=batch_size, 
                                          shuffle=False)

In [ ]:
'''
STEP 4: INSTANTIATE MODEL CLASS
'''
input_dim = 1
hidden_dim = 2
output_dim = 1

model = FeedforwardNeuralNetModel(input_dim, hidden_dim, output_dim)

'''
STEP 5: INSTANTIATE LOSS CLASS
'''

criterion = nn.MSELoss(reduction='mean')


'''
STEP 6: INSTANTIATE OPTIMIZER CLASS
'''
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)


'''
STEP 7: TRAIN THE MODEL
'''
iter = 0
num_epochs =2

for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):

        #######################
        #  USE GPU FOR MODEL  #
        #######################
        images = images.view(-1, 28*28).requires_grad_().to(device)
        labels = labels.to(device)

        # Clear gradients w.r.t. parameters
        optimizer.zero_grad()

        # Forward pass to get output/logits
        outputs = model(images)

        # Calculate Loss: softmax --> cross entropy loss
        loss = criterion(outputs, labels)

        # Getting gradients w.r.t. parameters
        loss.backward()

        # Updating parameters
        optimizer.step()

        iter += 1

        if iter % 500 == 0:
            # Calculate Accuracy         
            correct = 0
            total = 0
            # Iterate through test dataset
            for images, labels in test_loader:
                #######################
                #  USE GPU FOR MODEL  #
                #######################
                images = images.view(-1, 28*28).requires_grad_().to(device)

                # Forward pass only to get logits/output
                outputs = model(images)

                # Get predictions from the maximum value
                _, predicted = torch.max(outputs.data, 1)

                # Total number of labels
                total += labels.size(0)

                #######################
                #  USE GPU FOR MODEL  #
                #######################
                # Total correct predictions
                if torch.cuda.is_available():
                    correct += (predicted.cpu() == labels.cpu()).sum()
                else:
                    correct += (predicted == labels).sum()

            accuracy = 100 * correct / total

            # Print Loss
            print('Iteration: {}. Loss: {}. Accuracy: {}'.format(iter, loss.item(), accuracy))